### PR TITLE
[new facts module] Azure Cdn endpoint facts module

### PR DESCRIPTION
**Pull request by caohai**

### CODE REVIEW

**Comment by Fred-sun** [comment]
@caohai Thanks for the contribution. Could you help confirm the PR ready for review or not? if yes , I will push review. Thanks!

**Comment by Fred-sun** [comment]
@caohai Thanks for the contribution, Could you help confirm the PR finished change or not? If yes, I will push to review. Thanks!

**Comment by Fred-sun** [comment]
@caohai

**Comment by Fred-sun** [comment]
@caohai

**Comment by Fred-sun** [comment]
@caohai Thanks for the contribution, Are you still here? Could you help confirm the PR ready for review or not? It has no update more than two month. thanks!

**Comment by caohai** [comment]
@Fred-sun Sorry for late response. 
I believe this PR was ready for review then but no sure if any any extra change is needed. 
I'll close this PR for now, maybe it can be reopened later.

**Pull request closed without merging**
