### PR TITLE
Fix azure rm virtualmachinescalesetinstance doc

### PR DESCRIPTION
**Pull request by Fred-sun**
Fix azure rm virtualmachinescalesetinstance info doc, relate issue #310

### CODE REVIEW

**Comment by Fred-sun** [comment]
fixes #310

**Comment by Fred-sun** [comment]
ready_for_review

**Comment by Fred-sun** [comment]
@yungezz @acozine Can merge.

**Comment by yungezz** [comment]
@Fred-sun no need to involve ansible community for role PR's reviewing. thanks.

**Comment by Fred-sun** [comment]
@yungezz Ok, I see, thanks!

**Pull request merged**
