### PR TITLE
a bug fix for azure sqldatabase about elastic pool

### PR DESCRIPTION
**Pull request by MyronFanQiu**
##### SUMMARY

The Python SDK changed the parameter `elastic_pool_name` to the `elastic_pool_id` and cause the small bug for this module.
Ref:https://github.com/Azure/azure_preview_modules/issues/268

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME

azure_rm_sqldatabase

##### ADDITIONAL INFORMATION

Avoid including breaking change for the user, this PR preserve the ```elastic_pool_name``` as the input settings instead of supporting a dict

### CODE REVIEW

**Comment by Fred-sun** [comment]
@yungezz @yuwzho @zikalino Please help to review this PR when you're free! Thank you very much!

**Comment by Fred-sun** [comment]
@yungezz @zikalino Please help review this PR when you're free! Thanks a lot!

**Comment by Fred-sun** [comment]
ready_for_review

**Comment by Fred-sun** [comment]
@yungezz @MyronFanQiu This PR should also be merged, please help. Thank you very much!

**Comment by MyronFanQiu** [comment]
@Fred-sun we can close this one. The repo will sync up in Friday.

**Comment by MyronFanQiu** [comment]
@Fred-sun  Thanks.

**Pull request closed without merging**
