### PR TITLE
add condition for http status code

### PR DESCRIPTION
**Pull request by taaarpa6**
ensure that token_res returns a successful http status code before accessing the response

References
* https://github.com/Azure/azure_preview_modules/issues/336
* https://github.com/Azure/azure_preview_modules/issues/336#issuecomment-575235510

### CODE REVIEW

**Comment by Fred-sun** [comment]
@gavinfish @haiyuazhang

**Comment by Fred-sun** [comment]
ready_for_review

**Comment by jpdias92** [comment]
This PR solves the problem I was facing in issue #336.

Test procedure followed:

1. Uninstall azure preview modules: `ansible-galaxy remove azure.azure_preview_modules`
2. Run my playbook that makes use of this lookup plugin: `ansible-playbook _azure_keyvault_secret_lookup.yml`. Got the expected error `ERROR! the role 'azure.azure_preview_modules' was not found`
3. Install azure preview modules: `ansible-galaxy install azure.azure_preview_modules`
4. Run my playbook again `ansible-playbook _azure_keyvault_secret_lookup.yml`. Got the error described in issue #336 :
```
TASK [get secret] ***********************************************************************************************************************************
fatal: [localhost]: FAILED! => {"msg": "the field 'args' has an invalid value ({'secret_value': \"{{ lookup('azure_keyvault_secret', secretname, vault_url=url, client_id=client_id, secret=secret, tenant_id=tenant) }}\"}), and could not be converted to an dict.The error was: Expecting value: line 1 column 1 (char 0)\n\nThe error appears to be in '[path_removed]/_azure_keyvault_secret_lookup.yml': line 15, column
7, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n    - name: get secret\n      ^ here\n"}
```

5. Replace the file entire file `lookup_plugins/azure_keyvault_secret.py` with the new version added by this PR. Now my playbook runs successfully:
```
PLAY [localhost] ************************************************************************************************************************************
Thursday 06 February 2020  16:43:41 +0100 (0:00:00.064)       0:00:00.064 *****
Thursday 06 February 2020  16:43:41 +0100 (0:00:00.049)       0:00:00.113 *****
Thursday 06 February 2020  16:43:42 +0100 (0:00:00.088)       0:00:00.202 *****
Your credentials class does not support session injection. Performance will not be at the maximum.

TASK [get secret] ***********************************************************************************************************************************ok: [localhost]
Thursday 06 February 2020  16:43:43 +0100 (0:00:01.206)       0:00:01.408 *****

TASK [Look up secret when Ansible host is non-MSI VM] ***********************************************************************************************ok: [localhost] => {
    "secret_value": "[output_hidden]"
}

PLAY RECAP ******************************************************************************************************************************************localhost                  : ok=2    changed=0    unreachable=0    failed=0    skipped=2    rescued=0    ignored=0
```

So this confirms that indeed this PR solves an existent problem.

**Comment by Fred-sun** [comment]
@gavinfish @haiyuazhang Would you please help review and push for the PR merge when you're free? Thank you very much!

**Comment by taaarpa6** [comment]
@gavinfish thank you for the approval
@Fred-sun do you have the permission to merge this pull request?
thank you in advance!

**Comment by Fred-sun** [comment]
> @gavinfish thank you for the approval
> @Fred-sun do you have the permission to merge this pull request?
> thank you in advance!

@taaarpa6 I also have no permission to merge this PR, I will ping others to help merge. Thank you very much!

**Comment by Fred-sun** [comment]
@haiyuazhang Could you please help push for the PR merge! Thank you very much!

**Comment by Fred-sun** [comment]
@taaarpa6 Thank you for taking the time to contribute to this PR. We will transfer ansible 's azure module related Issue and PR to azure collection (https://github.com/ansible-collections/azure/pulls), can you transfer the Issue to azure collection repo?

**Comment by taaarpa6** [comment]
@Fred-sun Thank you very much for your support and your message! I will close this pull request and verify, if this change / fix is required for the azure collection. Maybe the error handling was already done properly.

**Pull request closed without merging**
