### PR TITLE
adds application gateway features

### PR DESCRIPTION
**Pull request by mjhoffman65**
Adds ability to manage probes, redirects and ssl certificates

### CODE REVIEW

**Comment by mjhoffman65** [comment]
All the tests seem to be failing due to an issue getting Azure credentials
```
{"changed": false, "msg": "Failed to get credentials. Either pass as parameters, set environment variables, define a profile in ~/.azure/credentials, or log in with Azure CLI (`az login`)."}
```

**Comment by mjhoffman65** [comment]
@Fred-sun Yep, this is ready for feedback.  Thanks for the reply

**Comment by Fred-sun** [comment]
@yungezz @yuwzho @zikalino Could you help review this PR?

**Comment by Fred-sun** [comment]
@yungezz @yuwzho @zikalino Could you help review this PR?

**Comment by Fred-sun** [comment]
@yungezz @yuwzho @zikalino Could you help review this PR?

**Comment by Fred-sun** [comment]
@yungezz @yuwzho @zikalino Could you help review this PR?

**Comment by mjhoffman65** [comment]
@yungezz @yuwzho @zikalino @Fred-sun is this the right repository to contribute to the Azure Ansible modules?

**Comment by yuwzho** [comment]
Hi @mjhoffman65 I am not clear with the context of Application gateway. But seems in the ansible repo, there is already an application_gateway module, while this one is a little bit out of date. @zikalino to provide more information. 

BTW, this repo is for Ansible role "[Azure.azure_preview_modules](https://galaxy.ansible.com/azure/azure_preview_modules)".

**Comment by zikalino** [comment]
@mjhoffman65 pls create pr to Ansible repo, where I can review it and merge. Appgateway module was renamed during the process of moving it there, your changes should be easily applied after renaming.

**Comment by Fred-sun** [comment]
@mjhoffman65 Thanks for the contribution, Could you help change according by @zikalino's advice? Thanks!

**Comment by mjhoffman65** [comment]
Thanks @yuwzho @zikalino @Fred-sun! I should be able to open up that PR this weekend.  Last couple of weeks has been a bit busy for me

**Comment by mjhoffman65** [comment]
@zikalino, opened up a PR against ansible here: https://github.com/ansible/ansible/pull/46607

**Pull request closed without merging**
