### PR TITLE
adds back in pip installation when skip_azure_sdk is false

### PR DESCRIPTION
**Pull request by coreywan**
This is a possible fix/suggestion for #237

### CODE REVIEW

**Comment by MyronFanQiu** [comment]
@coreywan Thanks for the contribution. I will push the following process of this PR forward.

**Comment by Fred-sun** [comment]
@yungezz @zikalino @yuwzho @MyronFanQiu Please help take a look this PR when you're free! Thanks a lot!

**Comment by Fred-sun** [comment]
@MyronFanQiu @yungezz This PR just adds a test case for PIPmodule. Can you help review and advance the merge? Thank you very much!

**Comment by MyronFanQiu** [comment]
@coreywan Hello. We have a discussion about this PR recently. The ansible does not recommend automatically installing all the dependency for the ansible role. 

For this PR, since the `skip_azure_sdk` is set to `true` which means it will not automatically install the dependency. It indeed supports an option to do this in the future and doesn't bring any behavior change for now. So it looks good to me.

**Comment by coreywan** [comment]
@MyronFanQiu,  Yes that is exactly the intent. `skip_azure_sdk` was put within the defaults folder to allow users/developers to override as needed.  Thanks!

**Comment by MyronFanQiu** [comment]
Thanks for your contribution!

**Pull request merged**
