### PR TITLE
Add azure_rm_keyvaultsecret_info module as per issue 308

### PR DESCRIPTION
**Pull request by imjoseangel**

### CODE REVIEW

**Comment by Fred-sun** [comment]
ready_for_review

**Comment by Fred-sun** [comment]
ready_for_review

**Comment by Fred-sun** [comment]
@mybayern1974 @haiyuazhang review_need

**Comment by Fred-sun** [comment]
@imjoseangel We also need to open a PR to https://github.com/ansible/ansible/pulls, Keep preview repo and devel repo in sync. Thank you very much!

**Comment by Fred-sun** [comment]
@haiyuazhang review_need!

**Comment by imjoseangel** [comment]
> @imjoseangel We also need to open a PR to https://github.com/ansible/ansible/pulls, Keep preview repo and devel repo in sync. Thank you very much!

Of course. This is it &rarr; https://github.com/ansible/ansible/pull/63160 . I can ensure both modules were synced after your review.

Thank you!

**Comment by devax** [comment]
Would be awessome if this PR could get merged. Waiting for that functionality.

**Comment by Fred-sun** [comment]
@imjoseangel Could you help resolve the conflicting files when you're free? It will push for PR meger and review! Thank you very much!

**Comment by imjoseangel** [comment]
@Fred-sun Test are failing when creating a VM, not because the module. Please confirm this can be merged too.

Thanks

**Comment by Fred-sun** [comment]
@imjoseangel It has been moved to #50 and merged. Can you close it? Thank you very much!

**Pull request closed without merging**
