### PR TITLE
adding mariadb to preview modules

### PR DESCRIPTION
**Pull request by zikalino**

### CODE REVIEW

**Comment by Fred-sun** [comment]
@zikalino  Could you help confirm that how about the PR going ahead? ready for review or need further update? Thanks!

**Comment by Fred-sun** [comment]
@yungezz @yuwzho

**Comment by Fred-sun** [comment]
@zikalino Could you help confirm that how about the PR going ahead? need changed or waiting for review?

**Comment by Fred-sun** [comment]
@zikalino

**Comment by Fred-sun** [comment]
@yungezz @yuwzho

**Comment by Fred-sun** [comment]
kindly ping

**Comment by Fred-sun** [comment]
kindly ping

**Comment by Fred-sun** [comment]
@zikalino Have you completed the change of PR? Thanks!

**Comment by zikalino** [comment]
closing as just being merged upstream

**Pull request closed without merging**
