### PR TITLE
fix: update keyvault access policies correctly

### PR DESCRIPTION
**Pull request by Eugen1987**
hi.

This PR  fix the issue #370

### CODE REVIEW

**Comment by Fred-sun** [comment]
@Eugen1987 Thank you for taking the time to contribute to this PR. We will ansible 's azure module related Issue and PR is transferred to azure collection (https://github.com/ansible-collections/azure/pulls), can you transfer the Issue to azure collection repo?

**Comment by Fred-sun** [comment]
Kindly ping!

**Comment by Eugen1987** [comment]
Sorry for not answering before, this is already in the collections-azure, it corresponds to:
azure_rm_keyvault module does not update access_policies for a keyvault #56

**Comment by Fred-sun** [comment]
> Sorry for not answering before, this is already in the collections-azure, it corresponds to:
> azure_rm_keyvault module does not update access_policies for a keyvault #56

Thanks for your udpate!

**Pull request closed without merging**
